language: generic
sudo: required
services:
  -docker

before_install:
  - docker build -t konungr/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true konungr/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-course"
  env: "Dockercourse-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-097114397865"
  bucket_path: "docker-course"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

